version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: ai_mail_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_mail
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: ai_mail_redis
    restart: always
    ports:
      - "6379:6379"